#!/bin/bash
read -p "using predefined message?" yn
if [[ "$yn" == "n" || "$yn" == "N" || "$yn" == "No" || "$yn" == "no" ]]
then
	echo "enter a commit message:"
	read first_message
	echo "commit message: ${first_message}"
	git add .
	git commit -m "${first_message}"
	git push https://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z@github.com/IvanNemirovskiy/learn-c.git
elif [[ "$yn" == "y" || "$yn" == "Y" || "$yn" == "Yes" || "$yn" == "yes" ]]
then
	export MESSAGE=$first_message
	echo "pushing with predefined message: $MESSAGE"
	git add .
	git commit -m "$MESSAGE"
	git push https://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@github.com/IvanNemirovskiy/learn-c.git
else
	echo "enter a commit message"
fi

export MESSAGE=${first_message}
